import type { Member } from "@/dashboard/admin/Members";
import type { ShepherdGroup } from "@/types/shepherd.types";

const MEMBERS: Member[] = [
  {
    id: "1",
    name: "Kwame Asante",
    institution: "KNUST",
    region: "Ashanti",
    programme: "Computer Science",
    shepherd: "Ama Owusu",
    phone: "+233 24 123 4567",
    status: "active",
    joined: "Jan 10, 2026",
  },
  {
    id: "2",
    name: "Ama Serwaa",
    institution: "UG Legon",
    region: "Greater Accra",
    programme: "Economics",
    shepherd: "Kojo Mensah",
    phone: "+233 20 987 6543",
    status: "active",
    joined: "Jan 12, 2026",
  },
  {
    id: "3",
    name: "Kofi Boateng",
    institution: "UCC",
    region: "Central",
    programme: "Civil Engineering",
    shepherd: "Unassigned",
    phone: "+233 55 456 7890",
    status: "pending",
    joined: "Jan 15, 2026",
  },
  {
    id: "4",
    name: "Abena Mensah",
    institution: "KNUST",
    region: "Ashanti",
    programme: "Architecture",
    shepherd: "Ama Owusu",
    phone: "+233 24 345 6789",
    status: "active",
    joined: "Jan 16, 2026",
  },
  {
    id: "5",
    name: "Yaw Darko",
    institution: "Ashesi",
    region: "Greater Accra",
    programme: "Business Admin",
    shepherd: "Unassigned",
    phone: "+233 50 234 5678",
    status: "pending",
    joined: "Jan 18, 2026",
  },
  {
    id: "6",
    name: "Akua Boateng",
    institution: "KNUST",
    region: "Ashanti",
    programme: "Medicine",
    shepherd: "Ama Owusu",
    phone: "+233 24 567 8901",
    status: "active",
    joined: "Jan 20, 2026",
  },
  {
    id: "7",
    name: "Nana Agyeman",
    institution: "UG Legon",
    region: "Greater Accra",
    programme: "Law",
    shepherd: "Kojo Mensah",
    phone: "+233 26 678 9012",
    status: "active",
    joined: "Jan 22, 2026",
  },
  {
    id: "8",
    name: "Efua Amponsah",
    institution: "UENR",
    region: "Brong-Ahafo",
    programme: "Nursing",
    shepherd: "Unassigned",
    phone: "+233 55 789 0123",
    status: "inactive",
    joined: "Jan 25, 2026",
  },
  {
    id: "9",
    name: "Kwabena Ofori",
    institution: "UMaT",
    region: "Western",
    programme: "Mining Engineering",
    shepherd: "Joe Frimpong",
    phone: "+233 27 890 1234",
    status: "active",
    joined: "Feb 1, 2026",
  },
  {
    id: "10",
    name: "Adwoa Frimpong",
    institution: "KNUST",
    region: "Ashanti",
    programme: "Pharmacy",
    shepherd: "Ama Owusu",
    phone: "+233 24 901 2345",
    status: "active",
    joined: "Feb 3, 2026",
  },
  {
    id: "11",
    name: "Kojo Antwi",
    institution: "UG Legon",
    region: "Greater Accra",
    programme: "Sociology",
    shepherd: "Kojo Mensah",
    phone: "+233 20 012 3456",
    status: "pending",
    joined: "Feb 5, 2026",
  },
  {
    id: "12",
    name: "Maame Konadu",
    institution: "UCC",
    region: "Central",
    programme: "Education",
    shepherd: "Unassigned",
    phone: "+233 55 123 4560",
    status: "active",
    joined: "Feb 8, 2026",
  },
];

const SHEPHERDS: ShepherdGroup[] = [
  {
    shepherd: "Ama Owusu",
    sessions: [
      {
        sheep: "Kwame Asante",
        institution: "KNUST",
        date: "Mar 24, 2026",
        status: "present",
        notes: "Bible study",
      },
      {
        sheep: "Ama Serwaa",
        institution: "KNUST",
        date: "Mar 24, 2026",
        status: "present",
        notes: "Bible study",
      },
      {
        sheep: "Abena Mensah",
        institution: "KNUST",
        date: "Mar 24, 2026",
        status: "absent",
        notes: "",
      },
      {
        sheep: "Akua Boateng",
        institution: "KNUST",
        date: "Mar 17, 2026",
        status: "present",
        notes: "Weekly check-in",
      },
      {
        sheep: "Adwoa Frimpong",
        institution: "KNUST",
        date: "Mar 17, 2026",
        status: "present",
        notes: "Weekly check-in",
      },
      {
        sheep: "Kwame Asante",
        institution: "KNUST",
        date: "Mar 10, 2026",
        status: "absent",
        notes: "",
      },
    ],
  },
  {
    shepherd: "Kojo Mensah",
    sessions: [
      {
        sheep: "Nana Agyeman",
        institution: "UG Legon",
        date: "Mar 24, 2026",
        status: "present",
        notes: "Weekly check-in",
      },
      {
        sheep: "Kojo Antwi",
        institution: "UG Legon",
        date: "Mar 24, 2026",
        status: "absent",
        notes: "Exams",
      },
      {
        sheep: "Nana Agyeman",
        institution: "UG Legon",
        date: "Mar 10, 2026",
        status: "present",
        notes: "Bible study",
      },
      {
        sheep: "Kojo Antwi",
        institution: "UG Legon",
        date: "Mar 3, 2026",
        status: "present",
        notes: "Prayer meeting",
      },
    ],
  },
  {
    shepherd: "Joe Frimpong",
    sessions: [
      {
        sheep: "Kwabena Ofori",
        institution: "UMaT",
        date: "Mar 17, 2026",
        status: "present",
        notes: "Prayer meeting",
      },
      {
        sheep: "Kwabena Ofori",
        institution: "UMaT",
        date: "Mar 3, 2026",
        status: "absent",
        notes: "",
      },
    ],
  },
];

export { SHEPHERDS };

export default MEMBERS;
