import type { Shepherd, PendingShepherd } from "./types";

export const SHEPHERDS: Shepherd[] = [
  {
    id: "s1",
    name: "Ama Owusu",
    email: "ama.owusu@gmail.com",
    phone: "+233 24 456 7890",
    institution: "KNUST",
    level: "400",
    position: "Welfare Officer",
    status: "active",
    joinedDate: "Jan 5, 2026",
    sheep: [
      {
        id: "m1",
        name: "Kwame Asante",
        institution: "KNUST",
        programme: "Computer Science",
        phone: "+233 24 123 4567",
        attendanceRate: 92,
      },
      {
        id: "m2",
        name: "Ama Serwaa",
        institution: "KNUST",
        programme: "Economics",
        phone: "+233 20 987 6543",
        attendanceRate: 85,
      },
      {
        id: "m3",
        name: "Abena Mensah",
        institution: "KNUST",
        programme: "Architecture",
        phone: "+233 24 345 6789",
        attendanceRate: 78,
      },
      {
        id: "m4",
        name: "Akua Boateng",
        institution: "KNUST",
        programme: "Medicine",
        phone: "+233 24 567 8901",
        attendanceRate: 100,
      },
      {
        id: "m5",
        name: "Adwoa Frimpong",
        institution: "KNUST",
        programme: "Pharmacy",
        phone: "+233 24 901 2345",
        attendanceRate: 71,
      },
    ],
  },
  {
    id: "s2",
    name: "Kojo Mensah",
    email: "kojo.mensah@gmail.com",
    phone: "+233 20 567 8901",
    institution: "UG Legon",
    level: "Postgraduate",
    position: "Bible Study Leader",
    status: "active",
    joinedDate: "Jan 8, 2026",
    sheep: [
      {
        id: "m6",
        name: "Nana Agyeman",
        institution: "UG Legon",
        programme: "Law",
        phone: "+233 26 678 9012",
        attendanceRate: 95,
      },
      {
        id: "m7",
        name: "Kojo Antwi",
        institution: "UG Legon",
        programme: "Sociology",
        phone: "+233 20 012 3456",
        attendanceRate: 60,
      },
    ],
  },
  {
    id: "s3",
    name: "Joe Frimpong",
    email: "joe.frimpong@gmail.com",
    phone: "+233 27 678 9012",
    institution: "UMaT",
    level: "300",
    position: "",
    status: "inactive",
    joinedDate: "Feb 2, 2026",
    sheep: [
      {
        id: "m8",
        name: "Kwabena Ofori",
        institution: "UMaT",
        programme: "Mining Engineering",
        phone: "+233 27 890 1234",
        attendanceRate: 50,
      },
    ],
  },
];

export const PENDING: PendingShepherd[] = [
  {
    id: "p1",
    name: "Emmanuel Osei",
    email: "e.osei@gmail.com",
    phone: "+233 24 111 2222",
    institution: "KNUST",
    level: "400",
    programme: "Computer Engineering",
    region: "Ashanti",
    hostel: "Unity Hall",
    applied: "2 days ago",
    token: "tok_1",
  },
  {
    id: "p2",
    name: "Grace Adjei",
    email: "g.adjei@gmail.com",
    phone: "+233 20 333 4444",
    institution: "UG Legon",
    level: "300",
    programme: "Economics",
    region: "Greater Accra",
    hostel: "Commonwealth Hall",
    applied: "3 days ago",
    token: "tok_2",
  },
  {
    id: "p3",
    name: "Daniel Frimpong",
    email: "d.frimpong@gmail.com",
    phone: "+233 55 555 6666",
    institution: "UCC",
    level: "Postgraduate",
    programme: "MBA",
    region: "Central",
    hostel: "Off-campus",
    applied: "5 days ago",
    token: "tok_3",
  },
  {
    id: "p4",
    name: "Akosua Boateng",
    email: "a.boateng@gmail.com",
    phone: "+233 24 777 8888",
    institution: "KNUST",
    level: "200",
    programme: "Architecture",
    region: "Ashanti",
    hostel: "Queens Hall",
    applied: "5 days ago",
    token: "tok_4",
  },
  {
    id: "p5",
    name: "Yaw Asiedu",
    email: "y.asiedu@gmail.com",
    phone: "+233 50 999 0000",
    institution: "Ashesi",
    level: "400",
    programme: "Business Admin",
    region: "Greater Accra",
    hostel: "Off-campus",
    applied: "6 days ago",
    token: "tok_5",
  },
  {
    id: "p6",
    name: "Nana Amponsah",
    email: "n.amponsah@gmail.com",
    phone: "+233 26 121 3141",
    institution: "UG Legon",
    level: "300",
    programme: "Law",
    region: "Greater Accra",
    hostel: "Mensah Sarbah",
    applied: "1 week ago",
    token: "tok_6",
  },
  {
    id: "p7",
    name: "Kofi Owiredu",
    email: "k.owiredu@gmail.com",
    phone: "+233 24 516 1718",
    institution: "KNUST",
    level: "400",
    programme: "Mechanical Eng",
    region: "Ashanti",
    hostel: "University Hall",
    applied: "1 week ago",
    token: "tok_7",
  },
  {
    id: "p8",
    name: "Abena Quansah",
    email: "a.quansah@gmail.com",
    phone: "+233 55 192 0212",
    institution: "UCC",
    level: "200",
    programme: "Education",
    region: "Central",
    hostel: "Off-campus",
    applied: "8 days ago",
    token: "tok_8",
  },
  {
    id: "p9",
    name: "Kwabena Darko",
    email: "kw.darko@gmail.com",
    phone: "+233 27 222 3232",
    institution: "UMaT",
    level: "300",
    programme: "Mining Engineering",
    region: "Western",
    hostel: "Off-campus",
    applied: "9 days ago",
    token: "tok_9",
  },
  {
    id: "p10",
    name: "Maame Serwaa",
    email: "m.serwaa@gmail.com",
    phone: "+233 55 343 4354",
    institution: "UENR",
    level: "Postgraduate",
    programme: "Nursing",
    region: "Brong-Ahafo",
    hostel: "Off-campus",
    applied: "10 days ago",
    token: "tok_10",
  },
];
